package br.com.olius.olius_core_api.exception.enums;

/** Códigos públicos estáveis. Não dependem de HTTP nem de mensagens do banco. */
public enum ApiErrorCode {
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    RESOURCE_CONFLICT,
    REGISTRATION_CONFLICT,
    DUPLICATE_TELEPHONE,
    PEV_ALREADY_EXISTS,
    BUSINESS_STATE_CONFLICT,
    BUSINESS_RULE_VIOLATION,
    CONCURRENT_MODIFICATION,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    NOT_ACCEPTABLE,
    HTTP_REQUEST_ERROR,
    INTERNAL_ERROR,
    SERVICE_UNAVAILABLE
}
