### Carregando variáveis do ".env" ###
spring.config.import=optional:file:.env[.properties]

### Nome da API ###
spring.application.name=olius-core-api

### Banco de dados ###
spring.datasource.url=${CONTAINER_DEV_URL}
spring.datasource.username=${CONTAINER_DEV_USER}
spring.datasource.password=${CONTAINER_DEV_PASSWORD}

### Hibernate ###
spring.jpa.hibernate.ddl-auto=validate